//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.7.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Annotations;

namespace Ex3_ModelManytoMany
{
   /// <inheritdoc/>
   public partial class EFModelOnetoMany : DbContext
   {
      #region DbSets
      public virtual System.Data.Entity.DbSet<global::Ex3_ModelManytoMany.Author> Authors { get; set; }
      public virtual System.Data.Entity.DbSet<global::Ex3_ModelManytoMany.Book> Books { get; set; }
      #endregion DbSets

      #region Constructors

      partial void CustomInit();

      /// <summary>
      /// Default connection string
      /// </summary>
      public static string ConnectionString { get; set; } = @"Data Source=(localdb)\dbinstance;Initial Catalog=EFLocalDb;Integrated Security=True";
      /// <inheritdoc />
      public EFModelOnetoMany() : base(ConnectionString)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(string connectionString) : base(connectionString)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(System.Data.Entity.Infrastructure.DbCompiledModel model) : base(model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModelOnetoMany(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext) : base(objectContext, dbContextOwnsObjectContext)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModelOnetoMany>(new EFModelOnetoManyDatabaseInitializer());
         CustomInit();
      }

      #endregion Constructors

      partial void OnModelCreatingImpl(System.Data.Entity.DbModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(System.Data.Entity.DbModelBuilder modelBuilder);

      /// <inheritdoc />
      protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<global::Ex3_ModelManytoMany.Author>()
                     .ToTable("Authors")
                     .HasKey(t => t.AuthorId);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Author>()
                     .Property(t => t.AuthorId)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Author>()
                     .Property(t => t.Firstname)
                     .HasMaxLength(125);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Author>()
                     .Property(t => t.Lastname)
                     .HasMaxLength(125);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Author>()
                     .HasMany(x => x.Books)
                     .WithRequired()
                     .Map(x => x.MapKey("AuthorBooksAuthorId"));

         modelBuilder.Entity<global::Ex3_ModelManytoMany.Book>()
                     .ToTable("Books")
                     .HasKey(t => t.BookId);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Book>()
                     .Property(t => t.BookId)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Book>()
                     .Property(t => t.Title)
                     .HasMaxLength(255);
         modelBuilder.Entity<global::Ex3_ModelManytoMany.Book>()
                     .Property(t => t.ISBN)
                     .HasMaxLength(75);

         OnModelCreatedImpl(modelBuilder);
      }
   }
}
