// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandbox_EFCore5NetCore3_Test;

namespace Sandbox_EFCore5Net5_Test.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210122110825_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Sandbox_EFCore5NetCore3_Test.Entity1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Entity1");
                });

            modelBuilder.Entity("Sandbox_EFCore5NetCore3_Test.Entity2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("Entity1Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Property1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Entity1Id");

                    b.ToTable("Entity2");
                });

            modelBuilder.Entity("Sandbox_EFCore5NetCore3_Test.Entity2", b =>
                {
                    b.HasOne("Sandbox_EFCore5NetCore3_Test.Entity1", "Entity1")
                        .WithMany("Entity2")
                        .HasForeignKey("Entity1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity1");
                });

            modelBuilder.Entity("Sandbox_EFCore5NetCore3_Test.Entity1", b =>
                {
                    b.Navigation("Entity2");
                });
#pragma warning restore 612, 618
        }
    }
}
