// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandbox_EFCore;

namespace Sandbox_EFCore.Migrations
{
    [DbContext(typeof(EFModel))]
    [Migration("20191026234521_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sandbox_EFCore.BaseClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BaseClasses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseClass");
                });

            modelBuilder.Entity("Sandbox_EFCore.Derived", b =>
                {
                    b.HasBaseType("Sandbox_EFCore.BaseClass");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Symbol")
                        .IsRequired();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasFilter("[Symbol] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Derived");
                });

            modelBuilder.Entity("Sandbox_EFCore.Derived2", b =>
                {
                    b.HasBaseType("Sandbox_EFCore.BaseClass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Derived2_Name");

                    b.Property<int?>("Optional_Id");

                    b.Property<int?>("Required_Id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnName("Derived2_Symbol");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Derived2_Name] IS NOT NULL");

                    b.HasIndex("Optional_Id");

                    b.HasIndex("Required_Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasFilter("[Derived2_Symbol] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Derived2");
                });

            modelBuilder.Entity("Sandbox_EFCore.Derived2", b =>
                {
                    b.HasOne("Sandbox_EFCore.Derived", "Optional")
                        .WithMany("NotCascading")
                        .HasForeignKey("Optional_Id");

                    b.HasOne("Sandbox_EFCore.Derived", "Required")
                        .WithMany("Cascading")
                        .HasForeignKey("Required_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
