//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.1.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Migrations;

namespace Migrations
{
   /// <inheritdoc/>
   public sealed partial class PersonModelDbMigrationConfiguration : DbMigrationsConfiguration<Ex1_Person.PersonModel>
   {
      partial void Init();

      /// <inheritdoc/>
      public PersonModelDbMigrationConfiguration()
      {
         AutomaticMigrationsEnabled = true;
         AutomaticMigrationDataLossAllowed = false;
         Init();
      }
   }
}
