//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace EFDesignerCoreTest
{
   public partial class EntityRelated
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected EntityRelated()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static EntityRelated CreateEntityRelatedUnsafe()
      {
         return new EntityRelated();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="entityabstract"></param>
      public EntityRelated(global::EFDesignerCoreTest.EntityAbstract entityabstract)
      {
         if (entityabstract == null) throw new ArgumentNullException(nameof(entityabstract));
         this.EntityAbstract = entityabstract;
         entityabstract.EntityRelated.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="entityabstract"></param>
      public static EntityRelated Create(global::EFDesignerCoreTest.EntityAbstract entityabstract)
      {
         return new EntityRelated(entityabstract);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// </summary>
      [Key]
      [Required]
      public long Id { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::EFDesignerCoreTest.EntityAbstract EntityAbstract { get; set; }

   }
}

