//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Sandbox_EF6_Test
{
   public partial class Entity2
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Entity2()
      {
         Init();
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Indexed
      /// Foreign key for Entity1.Entity2 &lt;--&gt; Entity2.Entity1. 
      /// </summary>
      [System.ComponentModel.Description("Foreign key for Entity1.Entity2 <--> Entity2.Entity1. ")]
      public int? FK { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual global::Sandbox_EF6_Test.Entity1 Entity1 { get; set; }

   }
}

