//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace MultiContext.Context2
{
   public partial class Entity3
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Entity3()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Entity3 CreateEntity3Unsafe()
      {
         return new Entity3();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="fk">Foreign key for Entity2.Entity3 --&gt; Entity3. </param>
      /// <param name="_entity20"></param>
      public Entity3(int fk, global::MultiContext.Context2.Entity2 _entity20)
      {
         this.Fk = fk;

         if (_entity20 == null) throw new ArgumentNullException(nameof(_entity20));
         _entity20.Entity3.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="fk">Foreign key for Entity2.Entity3 --&gt; Entity3. </param>
      /// <param name="_entity20"></param>
      public static Entity3 Create(int fk, global::MultiContext.Context2.Entity2 _entity20)
      {
         return new Entity3(fk, _entity20);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      public string Property1 { get; set; }

      /// <summary>
      /// Identity, Indexed, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Indexed, Required
      /// Foreign key for Entity2.Entity3 --&gt; Entity3. 
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Foreign key for Entity2.Entity3 --> Entity3. ")]
      public int Fk { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

   }
}

