// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFModelGenerator.WriteNavigationProperties(Sawczyn.EFDesigner.EFModel.ModelClass)")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFCoreModelGenerator.ConfigureBidirectionalAssociations(Sawczyn.EFDesigner.EFModel.ModelClass,System.Collections.Generic.List{Sawczyn.EFDesigner.EFModel.Association},System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFCoreModelGenerator.CreateForeignKeySegment(Sawczyn.EFDesigner.EFModel.Association,System.Collections.Generic.List{System.String})~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFCoreModelGenerator.ConfigureUnidirectionalAssociations(Sawczyn.EFDesigner.EFModel.ModelClass,System.Collections.Generic.List{Sawczyn.EFDesigner.EFModel.Association},System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFCore5ModelGenerator.ConfigureUnidirectionalAssociations(Sawczyn.EFDesigner.EFModel.ModelClass,System.Collections.Generic.List{Sawczyn.EFDesigner.EFModel.Association},System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "Full qualification needed in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.EFCore5ModelGenerator.ConfigureBidirectionalAssociations(Sawczyn.EFDesigner.EFModel.ModelClass,System.Collections.Generic.List{Sawczyn.EFDesigner.EFModel.Association},System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Parameter used in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.PushIndent(System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Parameter used in .ttinclude file", Scope = "member", Target = "~M:Sawczyn.EFDesigner.EFModel.EditingOnly.GeneratedTextTransformation.WriteLine(System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Members parallel vsct resources", Scope = "member", Target = "~F:Sawczyn.EFDesigner.EFModel.EFModelCommandSet.grpidEFDiagram")]
