// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sawczyn.EFDesigner.EFModel.DslPackage
{
    internal sealed partial class Vsix
    {
        public const string Id = "56bbe1ba-aaee-4883-848f-e3c8656f8db2";
        public const string Name = "Entity Framework Visual Editor";
        public const string Description = @"Entity Framework visual editor for EF6, EFCore and beyond.";
        public const string Language = "en-US";
        public const string Version = "2.0.5.4";
        public const string Author = "Michael Sawczyn";
        public const string Tags = "";
    }
}
