//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.1.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace Ex7_Mvp.Models
{
   /// <inheritdoc/>
   public partial class EFContainerDatabaseInitializer : MigrateDatabaseToLatestVersion<Ex7_Mvp.Models.EFContainer, Ex7_Mvp.Migrations.EFContainerDbMigrationConfiguration>
   {
   }
}
